// <auto-generated />
using System;
using JustBlog.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JustBlog.Core.Migrations
{
    [DbContext(typeof(JustBlogContext))]
    partial class JustBlogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JustBlog.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Arcu vel porta sollicitudin adipiscing euismod maecenas bibendum dui elementum fermentum pharetra",
                            Name = "Varius tempor",
                            UrlSlug = "volutpat-interdum"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Porttitor vel eu bibendum mauris id conubia porta justo nam luctus quam",
                            Name = "Tortor pulvinar",
                            UrlSlug = "aliquet-dictumst"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Lectus ac eleifend eget quam sagittis vel platea consectetur vivamus non porta",
                            Name = "Et odio",
                            UrlSlug = "pulvinar-tristique"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Diam ante aptent nulla elit at malesuada finibus aenean euismod pretium vitae",
                            Name = "Ligula laoreet",
                            UrlSlug = "porta-nec"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nostra pellentesque nisi nunc risus enim sem lacinia et rutrum erat felis",
                            Name = "Dui laoreet",
                            UrlSlug = "elementum-interdum"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Amet quisque orci sapien quis vulputate consequat laoreet malesuada nisl enim tincidunt",
                            Name = "Leo nam",
                            UrlSlug = "bibendum-magna"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Tempor adipiscing eros quisque orci massa quis himenaeos litora ad nibh enim",
                            Name = "Amet eu",
                            UrlSlug = "tellus-sagittis"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Elit proin rhoncus sit non mollis iaculis consequat feugiat eros morbi nulla",
                            Name = "Viverra urna",
                            UrlSlug = "rhoncus-ultrices"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Accumsan erat facilisis amet metus neque bibendum molestie nam eget felis dictum",
                            Name = "Laoreet massa",
                            UrlSlug = "varius-lacus"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Arcu ornare sagittis mollis euismod faucibus commodo nullam dignissim blandit tempor eros",
                            Name = "Felis mattis",
                            UrlSlug = "lacus-blandit"
                        });
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CommentHeader")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(1026)
                        .HasColumnType("nvarchar(1026)");

                    b.Property<DateTime>("CommentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PostId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentHeader = "Nibh eu sodales",
                            CommentText = "Erat, ac, orci, leo ex non torquent nisi, pretium eleifend nostra.",
                            CommentTime = new DateTime(2023, 9, 1, 2, 44, 12, 888, DateTimeKind.Local).AddTicks(8834),
                            Email = "commodo@amet.com",
                            Name = "Nulla neque",
                            PostId = 4
                        },
                        new
                        {
                            Id = 2,
                            CommentHeader = "Quisque eros urna",
                            CommentText = "Lectus massa amet sociosqu aliquet erat platea placerat, sodales maecenas ultricies tempor, quisque.",
                            CommentTime = new DateTime(2023, 8, 31, 3, 17, 12, 888, DateTimeKind.Local).AddTicks(9949),
                            Email = "sed@aliquet.com",
                            Name = "Ex leo",
                            PostId = 1
                        },
                        new
                        {
                            Id = 3,
                            CommentHeader = "Sem ullamcorper vulputate",
                            CommentText = "Adipiscing tempor, orci, finibus lorem, arcu, porta, a, mauris, nisl quisque sed taciti ligula, elit et sem.",
                            CommentTime = new DateTime(2023, 9, 2, 17, 56, 12, 889, DateTimeKind.Local).AddTicks(1036),
                            Email = "tortor@nullam.com",
                            Name = "Cras aptent",
                            PostId = 5
                        },
                        new
                        {
                            Id = 4,
                            CommentHeader = "Placerat euismod ante",
                            CommentText = "Ligula auctor nam euismod, eros, condimentum ligula, hac finibus euismod a odio, adipiscing metus sollicitudin dictumst. Morbi rhoncus consequat porta tincidunt feugiat, integer quam, nisi, lacinia, phasellus ultricies.",
                            CommentTime = new DateTime(2023, 9, 2, 10, 43, 12, 889, DateTimeKind.Local).AddTicks(2346),
                            Email = "nam@posuere.com",
                            Name = "Auctor massa",
                            PostId = 9
                        },
                        new
                        {
                            Id = 5,
                            CommentHeader = "Morbi pellentesque aptent",
                            CommentText = "Eu, volutpat vitae, auctor luctus, dictum porttitor cursus taciti dolor ipsum. Turpis interdum massa maximus dolor varius commodo, dui ad neque diam erat elit, facilisis pulvinar, augue vestibulum, urna, dapibus.",
                            CommentTime = new DateTime(2023, 8, 31, 0, 59, 12, 889, DateTimeKind.Local).AddTicks(3761),
                            Email = "nisi@adipiscing.com",
                            Name = "Ornare bibendum",
                            PostId = 2
                        },
                        new
                        {
                            Id = 6,
                            CommentHeader = "Quisque augue sem",
                            CommentText = "Nunc in elit, bibendum, ex, imperdiet vitae, tempor in, nostra, praesent euismod fusce porta, euismod, lorem. Sed odio, auctor inceptos nibh, felis sodales quis, tortor quisque non lobortis quis ultricies vel, tortor, erat, class et.",
                            CommentTime = new DateTime(2023, 9, 7, 23, 52, 12, 889, DateTimeKind.Local).AddTicks(5104),
                            Email = "per@aliquam.com",
                            Name = "Massa commodo",
                            PostId = 8
                        },
                        new
                        {
                            Id = 7,
                            CommentHeader = "Auctor odio urna",
                            CommentText = "Ligula scelerisque cras arcu, vel nisi, consequat dictum convallis rutrum cursus leo, tempus ut mattis. Fringilla in, donec ut nunc, a, hendrerit nam faucibus nisi magna, congue torquent arcu, himenaeos rutrum ante ex, eleifend.",
                            CommentTime = new DateTime(2023, 9, 1, 3, 40, 12, 889, DateTimeKind.Local).AddTicks(6474),
                            Email = "tempor@pellentesque.com",
                            Name = "Turpis sagittis",
                            PostId = 4
                        },
                        new
                        {
                            Id = 8,
                            CommentHeader = "Enim rhoncus ut",
                            CommentText = "Bibendum, elit, tincidunt quam, ornare orci, ut cursus, ultricies tempor dolor, aliquam sagittis, posuere, turpis dictum. Fusce eleifend, mattis, scelerisque at, duis vel urna blandit eleifend dolor leo lectus, cursus.",
                            CommentTime = new DateTime(2023, 8, 31, 20, 0, 12, 889, DateTimeKind.Local).AddTicks(7826),
                            Email = "est@neque.com",
                            Name = "Massa rhoncus",
                            PostId = 9
                        },
                        new
                        {
                            Id = 9,
                            CommentHeader = "Nunc inceptos dolor",
                            CommentText = "Sed, leo quam, amet, dapibus per vel, nibh, quis, in erat, nostra, ante mollis pretium fusce eu, a, bibendum. Nostra, luctus, litora quam, pulvinar, adipiscing quam nibh, commodo, dui in eleifend dictum fusce ac rutrum.",
                            CommentTime = new DateTime(2023, 9, 4, 3, 10, 12, 889, DateTimeKind.Local).AddTicks(9134),
                            Email = "mauris@bibendum.com",
                            Name = "Non elit",
                            PostId = 6
                        },
                        new
                        {
                            Id = 10,
                            CommentHeader = "Rutrum feugiat lorem",
                            CommentText = "Bibendum etiam leo arcu taciti bibendum, class vitae, sed, ante rutrum mi inceptos blandit, eros, primis euismod, fames pulvinar. Augue tempor, at justo fringilla finibus accumsan est rutrum porta varius, pellentesque metus porttitor tristique ornare urna.",
                            CommentTime = new DateTime(2023, 9, 7, 23, 32, 12, 890, DateTimeKind.Local).AddTicks(478),
                            Email = "feugiat@egestas.com",
                            Name = "Vehicula mattis",
                            PostId = 8
                        });
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("Post Content");

                    b.Property<DateTime>("PostedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("Posted On");

                    b.Property<bool>("Published")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("RateCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Rate Count");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Short Description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("TotalRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Total Rate");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("View Count");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            PostContent = "Nibh quam, class mattis eleifend laoreet dignissim massa, nisi, lobortis a vitae, tristique. Phasellus turpis at ut conubia ultrices, eu bibendum, odio hac nec, tortor ante, a ante at, cras mollis. Cursus, blandit ad lorem viverra interdum nullam sem, quis malesuada sollicitudin auctor cursus. Suspendisse lorem ante eget pulvinar enim, volutpat consequat magna praesent blandit, fusce elit, facilisis bibendum, condimentum. Enim egestas sed, convallis fusce commodo, arcu, tincidunt scelerisque enim.",
                            PostedOn = new DateTime(2023, 9, 2, 8, 1, 12, 880, DateTimeKind.Local).AddTicks(968),
                            Published = true,
                            RateCount = 28,
                            ShortDescription = "Porttitor mi curabitur arcu mauris sociosqu gravida suscipit luctus odio lacinia congue sed",
                            Title = "Leo adipiscing porttitor",
                            TotalRate = 184,
                            UrlSlug = "aenean-iaculis-sed",
                            ViewCount = 253
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            PostContent = "Congue, ipsum libero erat vivamus sit tristique aptent vel, viverra rhoncus lacus nam. Lorem erat felis nam maximus pulvinar, vestibulum sagittis, mattis interdum ac, cursus tempor congue. Tortor, quam nec, nostra, diam eget porta et rhoncus, ligula, eleifend duis. Dolor, congue, sed vulputate per amet efficitur diam dapibus purus mauris, accumsan proin magna erat ipsum vehicula. Justo euismod, tempor nisi cras ante, odio ornare eu, nullam mattis fringilla vel, volutpat ultrices, nunc, eros hendrerit. Elit urna, varius pretium auctor amet sem laoreet, accumsan ligula. Odio, arcu, a, blandit dignissim maecenas posuere, mattis ante quam hendrerit nunc sollicitudin maximus vulputate volutpat, varius imperdiet.",
                            PostedOn = new DateTime(2023, 9, 2, 5, 53, 12, 880, DateTimeKind.Local).AddTicks(4117),
                            Published = true,
                            RateCount = 27,
                            ShortDescription = "Enim lacinia arcu scelerisque fringilla congue erat nullam sed laoreet maecenas tortor finibus",
                            Title = "Fringilla tellus posuere",
                            TotalRate = 200,
                            UrlSlug = "odio-quam-iaculis",
                            ViewCount = 288
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            PostContent = "Dictumst ultricies fusce eros, ut tincidunt feugiat taciti dui, rutrum sociosqu facilisis duis gravida fringilla, in. Nec, duis efficitur tortor bibendum, ante, dapibus vehicula dictum quis porta habitasse facilisis ultrices. Mauris maecenas ante, in primis convallis orci, platea porttitor, efficitur taciti eros, pulvinar, egestas odio, semper. Ex, a leo pulvinar, metus orci, vehicula ex porttitor euismod, velit libero aliquet. Lectus, imperdiet rutrum velit eu nibh placerat, dolor fringilla mollis. In cras nisi ultricies vitae dolor, aptent quam, faucibus amet primis mi praesent ultrices hac. Sit auctor, rhoncus, donec curabitur morbi fames taciti tortor, justo ornare nulla in, ad mi, euismod, lacus non sagittis.",
                            PostedOn = new DateTime(2023, 9, 7, 15, 24, 12, 880, DateTimeKind.Local).AddTicks(7250),
                            Published = true,
                            RateCount = 21,
                            ShortDescription = "Non vitae massa pellentesque proin urna neque tortor molestie non commodo porttitor in",
                            Title = "Ex sapien quam",
                            TotalRate = 164,
                            UrlSlug = "et-suscipit-lorem",
                            ViewCount = 127
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            PostContent = "Tempor, mi, porta, posuere quisque lacus lacinia placerat vel dolor, tincidunt bibendum, orci, per nibh lacinia, mauris quis. Lorem pulvinar, mollis fames maximus morbi non ligula, placerat est. Sollicitudin pretium scelerisque eleifend laoreet mattis vel mollis sagittis inceptos massa, lobortis sed ligula, tempor, integer porttitor, at eleifend. Sed, ultrices ultrices, mattis phasellus metus placerat, nec, nulla dignissim vehicula a quam finibus. Quis, commodo, feugiat, nisi risus adipiscing eros, ornare sit ultrices. Tempor fames leo nunc, imperdiet feugiat, dictumst libero mi, maecenas. Finibus, et, justo laoreet lacinia facilisis dolor lacinia, torquent turpis tempus elementum laoreet, vivamus.",
                            PostedOn = new DateTime(2023, 8, 31, 16, 22, 12, 881, DateTimeKind.Local).AddTicks(272),
                            Published = true,
                            RateCount = 23,
                            ShortDescription = "Fringilla nec interdum tortor porta vestibulum luctus malesuada bibendum posuere fusce dolor mauris",
                            Title = "Mollis purus litora",
                            TotalRate = 104,
                            UrlSlug = "pellentesque-cursus-fermentum",
                            ViewCount = 273
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            PostContent = "Interdum, maximus fringilla, at urna, nibh ultrices ad urna curabitur primis magna blandit. Bibendum eu, egestas dignissim diam phasellus himenaeos lorem lectus hendrerit justo. Id phasellus sodales lectus, mi elit, morbi finibus auctor amet, tempus platea urna, vitae, ac molestie sapien integer. Dignissim sem, conubia pulvinar, vulputate neque hac vivamus turpis lobortis vel.",
                            PostedOn = new DateTime(2023, 9, 7, 21, 31, 12, 881, DateTimeKind.Local).AddTicks(2302),
                            Published = true,
                            RateCount = 21,
                            ShortDescription = "Ac taciti fermentum lorem blandit mattis tortor tristique integer ligula aliquet quis inceptos",
                            Title = "Amet ornare lacinia",
                            TotalRate = 274,
                            UrlSlug = "felis-luctus-et",
                            ViewCount = 244
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            PostContent = "Ultrices, lectus sed, pulvinar dictumst vestibulum laoreet, id platea adipiscing mattis ante, tellus sociosqu vitae, est fusce. Massa, felis augue auctor, magna, feugiat, sem, vestibulum, pellentesque arcu taciti eget elementum proin. Imperdiet quam, aliquet suspendisse mi, ex, tortor porta, scelerisque mi fringilla, non, tellus placerat, maximus. Turpis pharetra tellus odio tortor nisl mauris, eleifend, malesuada mattis, ultricies enim. Sagittis risus sem praesent urna, maximus porta, id vestibulum facilisis nulla, maecenas ligula, suscipit rutrum magna, non tempus. Quam maximus ante finibus eleifend, ante, commodo semper litora eget cursus placerat, sem, duis imperdiet.",
                            PostedOn = new DateTime(2023, 9, 5, 9, 28, 12, 886, DateTimeKind.Local).AddTicks(8903),
                            Published = true,
                            RateCount = 15,
                            ShortDescription = "Volutpat auctor viverra praesent et ipsum hendrerit lobortis eget pellentesque hac elementum arcu",
                            Title = "Arcu dolor odio",
                            TotalRate = 153,
                            UrlSlug = "sollicitudin-purus-ex",
                            ViewCount = 132
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            PostContent = "Dolor lacus vestibulum a, imperdiet porttitor magna id, conubia lacinia dolor, rhoncus tellus, mauris blandit, gravida. In, nibh mattis, elit, purus mi malesuada gravida urna feugiat pulvinar. Vivamus vestibulum, urna vestibulum condimentum suspendisse mauris augue gravida nunc, vehicula dictumst massa placerat nisi, rhoncus ante dolor. Varius class vel, enim lacus mi a placerat, eleifend, vestibulum, odio, aliquet enim, adipiscing donec.",
                            PostedOn = new DateTime(2023, 9, 7, 8, 6, 12, 887, DateTimeKind.Local).AddTicks(1534),
                            Published = true,
                            RateCount = 23,
                            ShortDescription = "Aliquam interdum non rhoncus nibh sociosqu primis mi ultricies per amet malesuada at",
                            Title = "Commodo accumsan ullamcorper",
                            TotalRate = 225,
                            UrlSlug = "non-finibus-tempus",
                            ViewCount = 293
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            PostContent = "Cursus, phasellus vehicula tristique primis vel ad nullam ac, auctor, ex, tellus, ultricies erat tempor, cursus. Nec, sapien lobortis tempus venenatis fringilla, sociosqu erat nostra, vivamus condimentum eget massa. Inceptos auctor massa, platea sit urna, adipiscing ullamcorper magna et. Dictum inceptos egestas turpis quis, dapibus ultrices lacinia ligula, nullam ipsum enim, eleifend fusce dui. Laoreet consequat tincidunt maximus metus lobortis neque, a, sagittis quis. At, sapien odio, mauris sem, elementum cras porttitor dui, nostra, maecenas sem risus ultrices, ullamcorper fringilla, scelerisque posuere donec. Taciti est purus inceptos faucibus urna, mattis scelerisque aliquam vestibulum, nisi imperdiet a, ac rutrum cursus, semper tristique.",
                            PostedOn = new DateTime(2023, 9, 3, 3, 11, 12, 887, DateTimeKind.Local).AddTicks(4635),
                            Published = true,
                            RateCount = 25,
                            ShortDescription = "Luctus mi aenean maecenas quam ante luctus hendrerit mauris lacus interdum blandit sit",
                            Title = "Integer vulputate posuere",
                            TotalRate = 286,
                            UrlSlug = "pellentesque-rhoncus-mauris",
                            ViewCount = 259
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            PostContent = "Fringilla, odio turpis tortor rhoncus, eu litora arcu, ante, iaculis pretium sagittis eleifend, blandit, eu, lorem. Ultrices, pulvinar, feugiat, velit tempor interdum, arcu eu, at id. Nec, conubia elementum imperdiet risus cras libero aptent himenaeos sem, enim bibendum, placerat, fusce. Congue suspendisse eleifend praesent id, fusce velit nibh, litora vivamus vestibulum conubia odio, odio venenatis.",
                            PostedOn = new DateTime(2023, 9, 4, 4, 18, 12, 887, DateTimeKind.Local).AddTicks(6770),
                            Published = true,
                            RateCount = 19,
                            ShortDescription = "Lacus est luctus nisi enim vivamus urna eget nulla semper nostra phasellus id",
                            Title = "Elit non dapibus",
                            TotalRate = 201,
                            UrlSlug = "lorem-aliquet-sem",
                            ViewCount = 171
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            PostContent = "Primis fermentum vehicula class fames magna, sed, purus per donec habitasse tellus ipsum tempor. Massa, sed nunc nisi urna odio, porttitor, vitae, magna, vulputate adipiscing sagittis ut ultricies pulvinar, fames vehicula. Et finibus, tempus class iaculis gravida ullamcorper etiam justo laoreet, hendrerit arcu, cursus urna, quam, integer. Neque varius non quis, orci vestibulum erat, finibus ultricies lacinia eu nisi. Massa, lectus ipsum efficitur metus libero bibendum ante fusce curabitur. Volutpat nisi vulputate fusce nibh, dictum amet, lacus justo interdum tincidunt neque laoreet odio euismod, consequat pulvinar, nullam lorem. Lectus eu quam, interdum in, nisi nisi, magna ultricies auctor, morbi donec erat, metus.",
                            PostedOn = new DateTime(2023, 8, 31, 22, 52, 12, 887, DateTimeKind.Local).AddTicks(9603),
                            Published = true,
                            RateCount = 19,
                            ShortDescription = "Tempor luctus congue velit pretium magna ex ligula praesent dui convallis lorem placerat",
                            Title = "Laoreet donec mi",
                            TotalRate = 280,
                            UrlSlug = "iaculis-duis-nibh",
                            ViewCount = 230
                        });
                });

            modelBuilder.Entity("JustBlog.Core.Entities.PostTagMap", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTagMaps", (string)null);

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            TagId = 1
                        },
                        new
                        {
                            PostId = 2,
                            TagId = 2
                        },
                        new
                        {
                            PostId = 3,
                            TagId = 3
                        },
                        new
                        {
                            PostId = 4,
                            TagId = 4
                        },
                        new
                        {
                            PostId = 5,
                            TagId = 5
                        },
                        new
                        {
                            PostId = 6,
                            TagId = 6
                        },
                        new
                        {
                            PostId = 7,
                            TagId = 7
                        },
                        new
                        {
                            PostId = 8,
                            TagId = 8
                        },
                        new
                        {
                            PostId = 9,
                            TagId = 9
                        },
                        new
                        {
                            PostId = 10,
                            TagId = 10
                        });
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1026)
                        .HasColumnType("nvarchar(1026)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 24,
                            Description = "Nulla vel class nibh ultricies pulvinar sollicitudin magna ipsum elit aenean sodales luctus",
                            Name = "In feugiat suscipit",
                            UrlSlug = "cursus-semper-elit"
                        },
                        new
                        {
                            Id = 2,
                            Count = 14,
                            Description = "Ultricies sed viverra ultrices tortor interdum pulvinar massa velit consectetur vel augue purus",
                            Name = "Massa rutrum mauris",
                            UrlSlug = "neque-scelerisque-fringilla"
                        },
                        new
                        {
                            Id = 3,
                            Count = 14,
                            Description = "Phasellus enim a nullam accumsan non in vitae feugiat laoreet imperdiet posuere elementum",
                            Name = "Convallis placerat finibus",
                            UrlSlug = "nunc-phasellus-consectetur"
                        },
                        new
                        {
                            Id = 4,
                            Count = 23,
                            Description = "Rhoncus dictum dui efficitur pharetra dolor justo vel fringilla mattis neque et ad",
                            Name = "Vitae tellus mauris",
                            UrlSlug = "consectetur-ad-felis"
                        },
                        new
                        {
                            Id = 5,
                            Count = 23,
                            Description = "Aptent sodales leo tortor ultrices faucibus vitae nisl lorem ultricies libero placerat phasellus",
                            Name = "Arcu massa quis",
                            UrlSlug = "lacinia-taciti-cras"
                        },
                        new
                        {
                            Id = 6,
                            Count = 15,
                            Description = "Bibendum dapibus efficitur eros faucibus dictumst eleifend elit nunc velit gravida vivamus cras",
                            Name = "Interdum libero fringilla",
                            UrlSlug = "congue-felis-id"
                        },
                        new
                        {
                            Id = 7,
                            Count = 21,
                            Description = "Placerat et fringilla eros vivamus enim feugiat quam quam volutpat inceptos nostra ex",
                            Name = "Non ex odio",
                            UrlSlug = "orci-vulputate-sapien"
                        },
                        new
                        {
                            Id = 8,
                            Count = 28,
                            Description = "Facilisis sem inceptos odio enim interdum volutpat dapibus lacinia malesuada accumsan nunc suspendisse",
                            Name = "Est dolor rhoncus",
                            UrlSlug = "curabitur-nulla-vitae"
                        },
                        new
                        {
                            Id = 9,
                            Count = 27,
                            Description = "Sodales orci lobortis nunc urna efficitur ligula interdum gravida laoreet hac erat integer",
                            Name = "Vitae massa vehicula",
                            UrlSlug = "finibus-elementum-hac"
                        },
                        new
                        {
                            Id = 10,
                            Count = 19,
                            Description = "Vitae rutrum odio arcu maecenas sodales nibh odio dui ex augue tortor congue",
                            Name = "At quam orci",
                            UrlSlug = "torquent-auctor-magna"
                        });
                });

            modelBuilder.Entity("JustBlog.Core.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AboutMe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "05ce7ad2-96c9-460b-a568-b4f0a8df9cd7",
                            AboutMe = "Ultrices congue quis varius mattis eu maximus eu ac pellentesque",
                            AccessFailedCount = 0,
                            Age = 43,
                            ConcurrencyStamp = "9bbff195-19a4-4da2-9f07-0b0775e8483b",
                            Email = "truongan123@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TRUONGAN123@GMAIL.COM",
                            NormalizedUserName = "TRUONGAN123",
                            PasswordHash = "AQAAAAEAACcQAAAAEO5k9kBvvLpdxhZaXWNZliqO8pydt5zxQleUVoR/oLBBq6J4bpz9FAHXpPrqTtot8A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6dc118c2-a4a4-4bf6-bcb7-16ab682d7730",
                            TwoFactorEnabled = false,
                            UserName = "truongan123"
                        },
                        new
                        {
                            Id = "1b4b227b-7ebb-4683-8560-e7367edd8ad9",
                            AboutMe = "Porttitor malesuada ornare blandit pellentesque hendrerit pretium ultrices augue phasellus",
                            AccessFailedCount = 0,
                            Age = 43,
                            ConcurrencyStamp = "226b1b3e-a835-421e-8d8c-77b157620bf4",
                            Email = "truongan1234@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TRUONGAN1234@GMAIL.COM",
                            NormalizedUserName = "TRUONGAN1234",
                            PasswordHash = "AQAAAAEAACcQAAAAEISddh/Bz6e5+sKWHQHYENfmrX/IdCOCC9fuqVFgjWSkVpxWOWZap249CjnHj7SQkw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9ea78498-97fd-4dfd-ae65-15b83fd8ecac",
                            TwoFactorEnabled = false,
                            UserName = "truongan1234"
                        },
                        new
                        {
                            Id = "83209156-f2e9-4e8e-b1c5-39d809d736b9",
                            AboutMe = "Eu lorem primis torquent eros dictumst platea per tempor ante",
                            AccessFailedCount = 0,
                            Age = 47,
                            ConcurrencyStamp = "ebc5ec7d-6e81-466a-be6e-ddce3cd18714",
                            Email = "truongan12345@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TRUONGAN12345@GMAIL.COM",
                            NormalizedUserName = "TRUONGAN12345",
                            PasswordHash = "AQAAAAEAACcQAAAAEPfjb22BnEoJ5qgDevG5u1T4aE87CkEfP7rHgbgeFQxwuaqHQEfEuSQzI4yaGdCM8g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6f0ec20f-0c50-49a1-83f3-fcbc0c9f0841",
                            TwoFactorEnabled = false,
                            UserName = "truongan12345"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e484c8c4-1e3f-4049-ac5a-26f0d81dcde8",
                            ConcurrencyStamp = "39ad0290-559c-4aaf-8604-f2f268f0e7b1",
                            Name = "Blog Owner",
                            NormalizedName = "BLOG OWNER"
                        },
                        new
                        {
                            Id = "f61e1d7f-8683-49cb-ab34-174cbda6dddb",
                            ConcurrencyStamp = "a809396c-c072-41c5-907c-00696f054ae6",
                            Name = "Contributor",
                            NormalizedName = "CONTRIBUTOR"
                        },
                        new
                        {
                            Id = "305bd8bf-90e0-4adb-8464-5985f70456ea",
                            ConcurrencyStamp = "d638a1d1-4bdf-4c5a-aee0-2d4e6d6d704b",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "15d38edc-87c6-4c1e-a3b9-26729c8e1269",
                            ConcurrencyStamp = "c4fa74ab-2974-4af3-a766-3b98947ca4e3",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "05ce7ad2-96c9-460b-a568-b4f0a8df9cd7",
                            RoleId = "e484c8c4-1e3f-4049-ac5a-26f0d81dcde8"
                        },
                        new
                        {
                            UserId = "1b4b227b-7ebb-4683-8560-e7367edd8ad9",
                            RoleId = "f61e1d7f-8683-49cb-ab34-174cbda6dddb"
                        },
                        new
                        {
                            UserId = "83209156-f2e9-4e8e-b1c5-39d809d736b9",
                            RoleId = "305bd8bf-90e0-4adb-8464-5985f70456ea"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Comment", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Post", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JustBlog.Core.Entities.PostTagMap", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.Post", "Post")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustBlog.Core.Entities.Tag", "Tag")
                        .WithMany("PostTagMaps")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustBlog.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("JustBlog.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostTagMaps");
                });

            modelBuilder.Entity("JustBlog.Core.Entities.Tag", b =>
                {
                    b.Navigation("PostTagMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
